apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatialanalysis
  namespace: spatialanalysis
spec:
  selector:
    matchLabels:
      app: spatialanalysis
  template:
    metadata:
      labels:
        app: spatialanalysis
  spec:
  containers:
    name: spatialanalysis
    image: perceptionengine.azurecr.io/cognitive-services-uvs-spatialanalysis:20231130.1
    imagePullSecrets:
      name: registry-credential
    imagePullPolicy: IfNotPresent