apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatialanalysis
  namespace: default
spec:
  selector:
    matchLabels:
      app: spatialanalysis
  template:
    metadata:
      labels:
        app: spatialanalysis
    spec:
      containers:
        - name: spatialanalysis
          image: rtptofficial.azurecr.io/cognitive-services-uvs-spatialanalysis:20231130.1
          imagePullPolicy: IfNotPresent