apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatialanalysis
  namespace: default
spec:
  selector:
    matchLabels:
      app: spatialanalysis
  template:
    metadata:
      labels:
        app: spatialanalysis
  spec:
  image: perceptionengine.azurecr.io/cognitive-services-uvs-spatialanalysis:20231130.1
  imagePullSecrets:
  - name: registry-credential
  imagePullPolicy: IfNotPresent
  interval: 5m0s